name: sync-container
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/deploy-container'
permissions:
  contents: read
env:
  GITHUB_REPO: "atrakic/go-static-site"
  BRANCH: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Static site generator 
        run: make site

      - name: Deploy
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git clone -q https://"${{ secrets.PERSONAL_TOKEN }}"@github.com/"${{ env.GITHUB_REPO }}".git "${{ env.GITHUB_REPO }}"
          rm -rf "${{ env.GITHUB_REPO }}"/_site
          mv -f _site "${{ env.GITHUB_REPO }}"/
          pushd "${{ env.GITHUB_REPO }}"
          git add -f _site
          git diff --name-only
          git commit --signoff -m "Sync site pages: ${{ env.GITHUB_SHA }}"
          git push -u origin "${{ env.BRANCH }}"
          popd
          rm -rf "${{ env.GITHUB_REPO }}"
